library("methylKit")

# -----------------------------------------------------------------------------
# Sample manifest helpers -----------------------------------------------------
# -----------------------------------------------------------------------------

#' Default metadata for the January 2019 methylation experiment.
#'
#' Returns a data.frame describing sample identifiers, group labels and the
#' expected file names for coverage and cytosine context outputs generated by
#' the methylKit Bismark pipeline.
default_methyl_manifest <- function() {
  data.frame(
    sample_id     = c("EH1516B", "EH1516C", "EH217A", "EH217B", "EH217C"),
    group         = c("EH1516", "EH1516", "EH217", "EH217", "EH217"),
    treatment     = c(0, 0, 1, 1, 1),
    coverage_file = c(
      "EH1516C.merged_CpG_evidence.cov",
      "EH1516D.merged_CpG_evidence.cov",
      "EH217A.merged_CpG_evidence.cov",
      "EH217B.merged_CpG_evidence.cov",
      "EH217C.merged_CpG_evidence.cov"
    ),
    CpG_file = c(
      "EH1516C_CpG.txt",
      "EH1516D_CpG.txt",
      "EH217A_CpG.txt",
      "EH217B_CpG.txt",
      "EH217C_CpG.txt"
    ),
    CHG_file = c(
      "EH1516C_CHG.txt",
      "EH1516D_CHG.txt",
      "EH217A_CHG.txt",
      "EH217B_CHG.txt",
      "EH217C_CHG.txt"
    ),
    stringsAsFactors = FALSE
  )
}

# Build a simple sample annotation table suitable for pheatmap::pheatmap.
build_sample_metadata <- function(manifest) {
  stopifnot(all(c("sample_id", "group") %in% names(manifest)))
  meta <- data.frame(strain = manifest$group, stringsAsFactors = FALSE)
  rownames(meta) <- manifest$sample_id
  return(meta)
}

# Internal utility to resolve file paths and optionally verify their existence.
resolve_file_paths <- function(base_dir, filenames, check_files = FALSE) {
  paths <- file.path(base_dir, filenames)
  if (isTRUE(check_files)) {
    missing <- paths[!file.exists(paths)]
    if (length(missing) > 0) {
      stop("Missing input files:\n", paste(missing, collapse = "\n"))
    }
  }
  return(paths)
}

# -----------------------------------------------------------------------------
# Data import helpers ---------------------------------------------------------
# -----------------------------------------------------------------------------

# Read Bismark CpG and CHG context files produced by processBismarkAln().
read_Bismark_CpG_CHG <- function(base_dir = "./",
                                 manifest = default_methyl_manifest(),
                                 assembly = "ehux", mincov = 3,
                                 check_files = FALSE, ...) {
  required_cols <- c("sample_id", "treatment", "CpG_file", "CHG_file")
  missing_cols <- setdiff(required_cols, names(manifest))
  if (length(missing_cols) > 0) {
    stop("Manifest is missing required columns: ", paste(missing_cols, collapse = ", "))
  }

  cpg_paths <- resolve_file_paths(base_dir, manifest$CpG_file, check_files)
  chg_paths <- resolve_file_paths(base_dir, manifest$CHG_file, check_files)

  methCpG <- methRead(
    cpg_paths,
    sample.id = manifest$sample_id,
    assembly = assembly,
    treatment = manifest$treatment,
    context = "CpG",
    pipeline = "bismark",
    mincov = mincov,
    ...
  )

  methCHG <- methRead(
    chg_paths,
    sample.id = manifest$sample_id,
    assembly = assembly,
    treatment = manifest$treatment,
    context = "CHG",
    pipeline = "bismark",
    mincov = mincov,
    ...
  )

  return(list(methCpG = methCpG, methCHG = methCHG))
}

# Read Bismark coverage files (CpG context) produced by methylKit.
read_Bismark_coverage <- function(base_dir = "./",
                                  manifest = default_methyl_manifest(),
                                  assembly = "ehux", mincov = 3,
                                  check_files = FALSE, ...) {
  required_cols <- c("sample_id", "treatment", "coverage_file")
  missing_cols <- setdiff(required_cols, names(manifest))
  if (length(missing_cols) > 0) {
    stop("Manifest is missing required columns: ", paste(missing_cols, collapse = ", "))
  }

  coverage_paths <- resolve_file_paths(base_dir, manifest$coverage_file, check_files)

  methobj <- methRead(
    coverage_paths,
    sample.id = manifest$sample_id,
    assembly = assembly,
    pipeline = "bismarkCoverage",
    treatment = manifest$treatment,
    context = "CpG",
    mincov = mincov,
    header = FALSE,
    ...
  )

  return(methobj)
}
